export const custosHelpContent = {
  "Custos — Início": {
    context: "O Laboratório de Custos transforma os dados técnicos das suas receitas em decisões de negócio: quanto custa produzir, quanto custa cada receita e cada porção, quanto cobrar e qual margem esse preço representa. Ele trabalha junto com o Laboratório de Cozinha, usando receitas, ingredientes, rendimentos, insumos e embalagens já cadastrados — sem obrigar você a refazer o trabalho.",
    faqs: [
      { q: "O que é o Laboratório de Custos?", a: "É o módulo que transforma os dados técnicos das suas receitas em custo de produção, custo por receita, custo por porção, preço de venda, margem e markup." },
      { q: "Qual é a diferença entre o Laboratório de Cozinha e o Laboratório de Custos?", a: "O Laboratório de Cozinha concentra receitas, ingredientes, rendimentos, porções, insumos e embalagens. O Laboratório de Custos usa esses dados para calcular custos do negócio e apoiar a formação do preço de venda." },
      { q: "Preciso cadastrar novamente minhas receitas no Laboratório de Custos?", a: "Não. As receitas são utilizadas diretamente a partir do Laboratório de Cozinha." },
      { q: "O Laboratório de Custos altera minha receita original?", a: "O cálculo, por si só, não altera a receita. Alterações só acontecem quando você escolhe explicitamente uma ação como 'Remover da receita'." },
      { q: "O que entra no cálculo do custo de uma receita?", a: "Podem entrar ingredientes, ingredientes esquecidos, insumos e embalagens da receita, itens adicionados especificamente ao cálculo e, quando ativado, o Custo do Negócio." },
      { q: "Qual é a diferença entre custo da receita, Custo do Negócio e preço de venda?", a: "O custo da receita representa os componentes diretamente ligados à produção. O Custo do Negócio distribui despesas gerais da atividade. O preço de venda é o valor que você pretende cobrar." },
      { q: "O que significa custo por receita?", a: "É o custo de produzir um rendimento completo da receita." },
      { q: "O que significa custo por porção?", a: "É o custo proporcional de uma porção, calculado a partir do rendimento e da porção cadastrada na receita." },
      { q: "O Laboratório de Custos substitui um sistema contábil ou financeiro?", a: "Não. Ele é uma ferramenta de cálculo gerencial para produção e formação de preço. Não substitui contabilidade, fluxo de caixa, estoque, folha de pagamento ou sistema fiscal." },
      { q: "Os meus cálculos ficam salvos?", a: "Sim, depois que você usa 'Salvar cálculo e gerar ficha'." },
      { q: "Se eu alterar uma receita, os cálculos antigos também mudam?", a: "Não. As fichas já salvas preservam os valores existentes no momento do cálculo." },
      { q: "Posso recalcular uma ficha antiga?", a: "Sim. O recálculo gera uma nova ficha com os valores atualizados sem apagar o histórico anterior." },
      { q: "Como iniciar um novo cálculo de custo?", a: "Clique em 'Calcular Custo' no menu lateral ou use o atalho disponível na tela Início." },
      { q: "Como abrir uma ficha de custo já calculada?", a: "Use a lista de cálculos recentes ou acesse 'Histórico'." },
      { q: "Onde cadastro as despesas do meu negócio?", a: "Em 'Minhas Despesas'." },
      { q: "Preciso configurar minhas despesas antes de calcular uma receita?", a: "Não necessariamente. Você pode calcular somente o custo técnico. Se quiser incluir despesas gerais, configure e ative o Custo do Negócio." },
      { q: "Posso calcular uma receita sem aplicar o Custo do Negócio?", a: "Sim. O Custo do Negócio é opcional e pode permanecer desligado." },
      { q: "Os valores da tela Início são atualizados quando faço um novo cálculo?", a: "Sim, depois que a nova ficha é salva." },
      { q: "A tela Início altera alguma informação das minhas receitas?", a: "Não. Ela apenas apresenta indicadores, cálculos recentes e atalhos." }
    ]
  },

  "Custos — Calcular Custo": {
    context: "Esta é a tela de trabalho do Laboratório de Custos. Você escolhe uma receita do Laboratório de Cozinha, informa quanto pretende produzir, confere os custos importados, decide se o Custo do Negócio entra no cálculo e forma o preço de venda. Enquanto você trabalha, o cálculo permanece como rascunho; ele só entra no Histórico quando você salva e gera a Ficha de Custo.",
    faqs: [
      { q: "Como localizar uma receita para calcular?", a: "Digite parte do nome da receita no campo de busca e selecione a opção desejada." },
      { q: "Quais receitas aparecem na busca?", a: "As receitas disponíveis para sua conta no Laboratório de Cozinha, incluindo suas receitas pessoais quando houver." },
      { q: "Posso calcular uma receita criada por mim?", a: "Sim. Receitas pessoais e receitas disponíveis no catálogo podem ser utilizadas no cálculo." },
      { q: "O que acontece se eu abrir 'Ver receita' durante o cálculo?", a: "O cálculo em andamento permanece como rascunho e é restaurado quando você volta ao Laboratório de Custos." },
      { q: "Meu cálculo é perdido se eu abrir a receita e depois voltar?", a: "Não. O rascunho preserva receita, quantidade, insumos adicionais e os dados de formação do preço enquanto você navega e volta." },
      { q: "O que significa 'Rascunho'?", a: "Significa que o cálculo está preenchido, mas ainda não foi registrado como Ficha de Custo." },
      { q: "Um rascunho já aparece no Histórico?", a: "Não. O Histórico contém somente fichas efetivamente salvas." },
      { q: "Quando o cálculo passa a fazer parte do Histórico?", a: "Depois de clicar em 'Salvar cálculo e gerar ficha' e o salvamento ser concluído." },
      { q: "Como trocar a receita que estou calculando?", a: "Pesquise e selecione outra receita. Os dados específicos do cálculo anterior são reiniciados para a nova seleção." },
      { q: "O que significa 'Quantidade de receitas'?", a: "É o número de rendimentos completos da receita que você pretende produzir." },
      { q: "O que significa produzir 1 receita?", a: "Produzir uma vez o rendimento completo cadastrado para aquela receita." },
      { q: "Se eu informar 20 receitas, o que será multiplicado?", a: "Os componentes proporcionais ao número de receitas são escalados para essa produção, respeitando a regra de cada ingrediente ou insumo." },
      { q: "O que é 'Rendimento estimado da produção'?", a: "É o rendimento completo da receita multiplicado pela quantidade de receitas informada." },
      { q: "Como o rendimento total é calculado?", a: "A partir do rendimento efetivo cadastrado na receita e da quantidade de receitas que você informou." },
      { q: "O que significa 'Nº de porções estimadas'?", a: "É a quantidade aproximada de porções obtida a partir do rendimento total produzido e da porção cadastrada na receita." },
      { q: "O número de porções altera a quantidade de receitas?", a: "Não. Ele serve para estimar o custo por porção e não modifica a quantidade de receitas produzidas." },
      { q: "Como é calculado o custo por porção?", a: "O custo total da produção é distribuído pela quantidade estimada de porções." },
      { q: "O que acontece se a porção da receita estiver incorreta?", a: "O custo por porção também poderá ficar incorreto. Corrija a porção na receita do Laboratório de Cozinha." },
      { q: "Posso produzir uma quantidade fracionada de receitas?", a: "Sim, quando isso fizer sentido para sua produção. O sistema aceita quantidade decimal." },
      { q: "O que entra em 'Ingredientes'?", a: "O custo dos ingredientes cadastrados na composição principal da receita, considerando a quantidade de receitas informada." },
      { q: "De onde vêm os preços dos ingredientes?", a: "Dos preços disponíveis para sua conta no Laboratório de Cozinha, respeitando seus dados pessoais de compra quando existirem." },
      { q: "O que são 'Insumos e embalagens importados da receita'?", a: "São materiais auxiliares ou embalagens que já estão registrados na receita e entram no custo técnico." },
      { q: "Como visualizar os insumos e embalagens importados?", a: "Clique em 'Ver itens' ao lado de 'Insumos e embalagens importados da receita'." },
      { q: "O que são 'Ingredientes esquecidos'?", a: "São itens de preparo, acabamento ou finalização que possuem custo, mas não fazem parte necessariamente da composição principal da receita." },
      { q: "Por que ingredientes esquecidos também entram no custo?", a: "Porque pequenas quantidades usadas para untar, polvilhar, decorar ou finalizar também representam custo real de produção." },
      { q: "Como visualizar os ingredientes esquecidos utilizados no cálculo?", a: "Clique em 'Ver itens' ao lado de 'Ingredientes esquecidos'." },
      { q: "Posso retirar um insumo apenas deste cálculo?", a: "Sim. Abra 'Ver itens' e escolha 'Não considerar neste cálculo'. A receita de origem permanece intacta." },
      { q: "Qual é a diferença entre 'Não considerar neste cálculo' e 'Remover da receita'?", a: "'Não considerar neste cálculo' afeta somente o cálculo atual. 'Remover da receita' altera a receita de origem e também afeta cálculos futuros." },
      { q: "Se eu remover um item da receita, os cálculos antigos serão alterados?", a: "Não. Fichas já salvas preservam os valores existentes na data em que foram geradas." },
      { q: "Posso excluir uma embalagem que não será utilizada nesta produção?", a: "Sim. Você pode desconsiderá-la somente neste cálculo ou removê-la da receita, quando essa opção estiver disponível." },
      { q: "Posso excluir um ingrediente esquecido somente deste cálculo?", a: "Sim. Use 'Não considerar neste cálculo'." },
      { q: "Por que alguns itens aparecem como 'Sem preço'?", a: "Porque não foi encontrado um preço válido para aquele item. O custo ficará incompleto até o cadastro ser corrigido ou o item ser desconsiderado, quando apropriado." },
      { q: "O que faço quando aparece uma pendência na receita?", a: "Revise o item indicado. A pendência pode ser preço ausente, referência inválida ou outro problema que comprometa a integridade do custo." },
      { q: "Posso salvar uma ficha enquanto houver pendências de custo?", a: "Não quando a pendência comprometer a integridade do cálculo. O sistema bloqueia o salvamento até a situação ser resolvida." },
      { q: "Quando devo usar 'Adicionar insumo não cadastrado'?", a: "Quando um item usado especificamente naquela produção ainda não estiver cadastrado na receita." },
      { q: "Um insumo adicionado aqui será cadastrado na receita?", a: "Não. Ele pertence somente ao cálculo atual. Para reutilizá-lo no futuro, cadastre-o na receita do Laboratório de Cozinha." },
      { q: "O que significa 'Por receita'?", a: "O valor informado será aplicado a cada receita produzida. Exemplo: R$ 2,50 por receita × 20 receitas = R$ 50,00." },
      { q: "O que significa 'Produção inteira'?", a: "O valor será considerado apenas uma vez no total da produção, independentemente do número de receitas." },
      { q: "Quando devo escolher 'Produção inteira'?", a: "Quando o custo informado se refere ao lote ou produção completa, e não a cada receita individualmente." },
      { q: "Posso adicionar mais de um insumo excepcional?", a: "Sim. Adicione quantos itens forem necessários para representar aquela produção." },
      { q: "Posso excluir um insumo que adicionei neste cálculo?", a: "Sim. Use a lixeira na própria linha do item." },
      { q: "Esse insumo aparecerá em cálculos futuros?", a: "Não. Itens adicionados nesta área existem somente no cálculo atual." },
      { q: "O que é o Custo do Negócio?", a: "É a parcela das despesas gerais da atividade distribuída entre as receitas produzidas." },
      { q: "De onde vem o valor do Custo do Negócio aplicado?", a: "Das despesas e dos parâmetros configurados em 'Minhas Despesas'." },
      { q: "Como o Custo do Negócio é distribuído entre as receitas?", a: "Conforme a base escolhida em 'Minhas Despesas': por Dia ou por Mês." },
      { q: "Qual é a diferença entre distribuição por Dia e por Mês?", a: "Na base Dia, o sistema considera dias de produção no mês e produção média diária. Na base Mês, considera diretamente a produção média mensal." },
      { q: "Posso fazer um cálculo sem aplicar o Custo do Negócio?", a: "Sim. Se a aplicação estiver desligada, o cálculo considera somente os demais componentes de custo." },
      { q: "O que significa 'Custo do Negócio não aplicado'?", a: "Significa que as despesas gerais cadastradas não estão sendo acrescentadas ao cálculo atual." },
      { q: "Despesas com pessoal podem entrar no Custo do Negócio?", a: "Sim. O grupo 'Despesas com pessoal' pode ser incluído entre os grupos considerados." },
      { q: "O Laboratório utiliza horas trabalhadas para calcular mão de obra?", a: "Não no modelo atual. O Custo do Negócio é distribuído pela produção, e não pelas horas gastas em cada receita." },
      { q: "O que significa 'Custo técnico importado'?", a: "É a soma dos componentes técnicos da receita importados do Laboratório de Cozinha: ingredientes, insumos, embalagens e ingredientes esquecidos considerados." },
      { q: "O que significa 'Custo total da produção'?", a: "É tudo o que está sendo considerado para produzir a quantidade informada, incluindo o Custo do Negócio quando ele estiver ativado." },
      { q: "O custo por receita já é o preço de venda?", a: "Não. Ele representa quanto custa produzir um rendimento completo. O preço de venda é definido no Passo 4." },
      { q: "Como o sistema calcula o preço de venda inicial?", a: "Ele parte do custo por receita e da margem inicial sugerida configurada. Esse valor é apenas um ponto de partida editável." },
      { q: "Por que a margem inicial sugerida é 20%?", a: "É apenas um ponto de partida operacional para facilitar o primeiro cálculo. Não representa uma regra obrigatória para o seu negócio." },
      { q: "A margem de 20% é obrigatória?", a: "Não. Você pode informar a margem, o markup ou o preço de venda que fizer sentido para sua realidade." },
      { q: "O que é margem?", a: "É o percentual do preço de venda que permanece após descontar o custo considerado." },
      { q: "O que é markup?", a: "É o multiplicador aplicado sobre o custo para chegar ao preço de venda. Exemplo: custo de R$ 100,00 com markup 1,25x gera preço de R$ 125,00." },
      { q: "Qual é a diferença entre margem e markup?", a: "Margem é percentual calculado sobre o preço de venda. Markup é um multiplicador aplicado ao custo." },
      { q: "Por que markup não é porcentagem?", a: "Porque ele representa uma relação multiplicativa, como 1,25x, 1,50x ou 2,00x." },
      { q: "Se eu alterar o preço de venda, o que acontece com margem e markup?", a: "Margem e markup são recalculados automaticamente." },
      { q: "Se eu alterar a margem, o que acontece com o preço?", a: "O preço de venda e o markup são recalculados automaticamente." },
      { q: "Se eu alterar o markup, o que acontece com o preço?", a: "O preço de venda e a margem são recalculados automaticamente." },
      { q: "Por que o último campo alterado passa a comandar o cálculo?", a: "Porque preço, margem e markup dependem matematicamente uns dos outros. O último campo alterado passa a ser a referência para evitar conflito entre valores." },
      { q: "Posso simplesmente informar o preço que pretendo cobrar?", a: "Sim. Informe o preço e o sistema calcula automaticamente a margem e o markup correspondentes." },
      { q: "O preço sugerido pelo sistema é obrigatório?", a: "Não. O sistema oferece apoio ao cálculo, mas a decisão comercial é sua." },
      { q: "O Laboratório determina qual margem devo utilizar?", a: "Não. A margem adequada depende da realidade do seu negócio, posicionamento, mercado e estratégia comercial." },
      { q: "O sistema considera impostos automaticamente?", a: "Não como cálculo fiscal individualizado. O modelo foi mantido simples e gerencial, sem substituir orientação contábil ou tributária." },
      { q: "O que é 'Formação avançada do preço'?", a: "É uma opção para formar o preço considerando a margem desejada e, quando ativado, o percentual médio de comercialização configurado." },
      { q: "Quando vale a pena utilizar a formação avançada?", a: "Quando você quiser analisar o preço além da relação direta entre custo, margem e markup e incluir o custo médio de comercialização." },
      { q: "O que é custo médio de comercialização?", a: "É um percentual global opcional para representar custos variáveis relacionados à comercialização, configurado em 'Minhas Despesas'." },
      { q: "O custo médio de comercialização entra sempre no preço?", a: "Não. Ele precisa estar ativado e é utilizado na formação avançada do preço." },
      { q: "Posso voltar da formação avançada para o cálculo simples?", a: "Sim. Basta editar novamente preço, margem ou markup na tela principal." },
      { q: "Como salvar o cálculo?", a: "Clique em 'Salvar cálculo e gerar ficha'." },
      { q: "O que significa 'Salvar cálculo e gerar ficha'?", a: "Significa registrar os valores atuais como uma Ficha de Custo histórica. A partir desse momento, o cálculo aparece no Histórico." },
      { q: "Por que sair da tela não salva automaticamente no Histórico?", a: "Porque o sistema diferencia um cálculo em andamento de uma ficha finalizada. Sair preserva o rascunho, mas não cria um registro histórico sem sua confirmação." },
      { q: "O que acontece com o rascunho se eu sair da tela?", a: "Ele permanece temporariamente salvo para você continuar o preenchimento quando voltar." },
      { q: "Quando o rascunho é apagado?", a: "Depois que a ficha é salva com sucesso ou quando outro fluxo substitui aquele cálculo." },
      { q: "Como sei se o cálculo realmente foi salvo?", a: "O sistema confirma o salvamento e abre a Ficha de Custo correspondente." },
      { q: "Onde encontro a ficha depois de salvar?", a: "Em 'Histórico'." }
    ]
  },

  "Custos — Ficha de Custo": {
    context: "A Ficha de Custo é o registro histórico de um cálculo finalizado. Ela guarda os valores usados naquele momento para que você consiga consultar, comparar e recalcular depois sem perder a memória do custo anterior. Alterações futuras em preços, receitas ou despesas não reescrevem uma ficha já salva.",
    faqs: [
      { q: "O que é a Ficha de Custo?", a: "É o registro final de um cálculo realizado para uma receita em determinada data." },
      { q: "Quais informações ficam registradas na ficha?", a: "Receita, produção, custos técnicos, Custo do Negócio, custo total, custo por receita, custo por porção e dados de formação de preço." },
      { q: "A ficha mostra os valores existentes na data do cálculo?", a: "Sim. Ela funciona como um snapshot do cálculo realizado naquele momento." },
      { q: "Se o preço de um ingrediente mudar depois, a ficha antiga também muda?", a: "Não. A ficha antiga preserva o valor utilizado quando foi salva." },
      { q: "O que significa preservar a ficha como histórico?", a: "Significa manter os valores originais do cálculo para consulta futura, mesmo que preços, receitas ou despesas mudem depois." },
      { q: "De onde vem o custo técnico registrado?", a: "Do Laboratório de Cozinha, conforme os dados existentes no momento em que o cálculo foi realizado." },
      { q: "Onde vejo o Custo do Negócio aplicado?", a: "Na composição de custos e nas informações complementares da ficha." },
      { q: "Onde vejo os insumos adicionais utilizados naquele cálculo?", a: "Nos itens registrados especificamente para aquela ficha, quando houver." },
      { q: "Como foi calculado o custo por receita?", a: "Custo total da produção ÷ quantidade de receitas produzidas." },
      { q: "Como foi calculado o custo por porção?", a: "Custo total da produção ÷ quantidade estimada de porções." },
      { q: "Como foi formado o preço de venda?", a: "A ficha registra o método e os parâmetros utilizados no momento do cálculo, como preço informado, margem ou formação avançada." },
      { q: "Como vejo a margem utilizada?", a: "Na seção de formação do preço da ficha." },
      { q: "Como vejo o markup utilizado?", a: "Na seção de formação do preço da ficha." },
      { q: "Como saber se foi utilizada formação avançada do preço?", a: "A ficha identifica o método de formação utilizado e apresenta os parâmetros correspondentes." },
      { q: "Posso editar uma ficha já salva?", a: "Não diretamente. A ficha é preservada como registro histórico." },
      { q: "Por que uma ficha salva não pode ser simplesmente alterada?", a: "Para preservar a rastreabilidade do cálculo e permitir comparar custos de momentos diferentes." },
      { q: "Como atualizar uma ficha quando os custos mudarem?", a: "Use a opção de recalcular para gerar uma nova ficha com os dados atuais." },
      { q: "O que significa recalcular uma ficha?", a: "Criar um novo cálculo da mesma receita utilizando os dados e preços atuais, sem apagar a ficha anterior." },
      { q: "O recálculo apaga a ficha anterior?", a: "Não. A ficha anterior continua preservada no Histórico." },
      { q: "A data do novo cálculo será atualizada?", a: "Sim. O novo cálculo recebe sua própria data." },
      { q: "Posso consultar fichas antigas mesmo depois de recalcular?", a: "Sim. As fichas anteriores permanecem disponíveis para consulta." },
      { q: "A ficha pode ser utilizada como registro interno do meu negócio?", a: "Sim. Ela foi projetada para preservar a memória dos custos e preços calculados ao longo do tempo." }
    ]
  },

  "Custos — Histórico": {
    context: "O Histórico reúne somente as Fichas de Custo que você decidiu salvar. Ele permite acompanhar como custo, preço e margem mudaram ao longo do tempo, pesquisar receitas, filtrar por período e reabrir cálculos antigos sem alterar seus valores originais.",
    faqs: [
      { q: "O que aparece no Histórico de Cálculos?", a: "As Fichas de Custo que foram efetivamente salvas." },
      { q: "Qual é a diferença entre Histórico e rascunho?", a: "O Histórico contém fichas finalizadas. O rascunho é um cálculo ainda em andamento e não aparece nesta tela." },
      { q: "Por que uma receita calculada não aparece imediatamente no Histórico?", a: "Porque o preenchimento precisa ser confirmado com 'Salvar cálculo e gerar ficha'." },
      { q: "Quando uma ficha entra no Histórico?", a: "Depois que o salvamento da Ficha de Custo é concluído com sucesso." },
      { q: "Posso pesquisar uma receita pelo nome?", a: "Sim. Use o campo 'Buscar receita'." },
      { q: "Como filtrar os cálculos por data?", a: "Utilize os campos 'De' e 'Até'." },
      { q: "Como filtrar por categoria?", a: "Use o seletor de Categoria. A categoria é um filtro auxiliar e também aparece no final da tabela." },
      { q: "O que significa 'Fichas salvas'?", a: "É a quantidade total de fichas registradas no seu Histórico." },
      { q: "O que significa 'Cálculos neste mês'?", a: "É a quantidade de fichas geradas no mês corrente." },
      { q: "Como é calculado o 'Custo médio por receita'?", a: "Pela média dos custos por receita das fichas salvas consideradas pelo indicador." },
      { q: "O que significa 'Formações avançadas'?", a: "É a quantidade de fichas em que foi utilizado o modo avançado de formação do preço." },
      { q: "Por que uma mesma receita pode aparecer mais de uma vez?", a: "Porque a mesma receita pode ser calculada em datas diferentes. Cada ficha preserva os valores daquele momento." },
      { q: "Como identificar quando cada cálculo foi realizado?", a: "Pela coluna 'Data do cálculo'." },
      { q: "Se eu recalcular uma receita, o cálculo anterior continuará aqui?", a: "Sim. O histórico anterior não é apagado." },
      { q: "Como abrir uma Ficha de Custo?", a: "Clique no nome da receita ou use 'Ações' → 'Abrir ficha'." },
      { q: "Como recalcular uma ficha?", a: "Abra o menu de Ações e escolha 'Recalcular como nova versão'. O sistema usa a ficha como ponto de partida e cria um novo cálculo." },
      { q: "Por que alguns cálculos antigos não podem ser recalculados diretamente?", a: "Para manter uma sequência histórica coerente, novos recálculos devem partir do cálculo mais recente daquela sequência." },
      { q: "O que significa 'Existe versão posterior' nas ações?", a: "Significa que aquela ficha já foi recalculada e existe um cálculo mais recente. A informação de versão é mantida internamente, mesmo sem aparecer como selo na tabela." },
      { q: "Por que a versão não aparece na tabela?", a: "Porque a data do cálculo é suficiente para a consulta cotidiana. O versionamento continua preservado internamente para rastreabilidade." },
      { q: "Posso excluir uma ficha do Histórico?", a: "A exclusão não faz parte do fluxo normal. O modelo prioriza preservar a memória dos cálculos realizados." },
      { q: "Por que o Histórico preserva os valores antigos?", a: "Para que você consiga saber quanto custava produzir e vender uma receita em cada momento." },
      { q: "O Histórico muda quando altero uma receita no Laboratório de Cozinha?", a: "Não. Fichas salvas permanecem congeladas com os valores da data do cálculo." },
      { q: "Como localizar rapidamente uma receita quando houver muitas fichas salvas?", a: "Use a busca por nome e os filtros de data e categoria. A tabela também mantém a coluna Receita fixa durante a rolagem horizontal." }
    ]
  },

  "Custos — Minhas Despesas": {
    context: "Minhas Despesas transforma os gastos mensais do negócio em uma parcela de custo que pode ser distribuída entre as receitas. Você escolhe o que deseja considerar, informa sua realidade de produção e decide se esse Custo do Negócio deve entrar ou não nos cálculos. A ideia é incluir despesas reais sem transformar o Laboratório em um sistema contábil.",
    faqs: [
      { q: "O que devo cadastrar em Minhas Despesas?", a: "As despesas mensais do negócio que você deseja considerar na formação dos seus custos." },
      { q: "Quais despesas realmente devem entrar no cálculo?", a: "Aquelas que fazem sentido para sua operação. Você decide quais despesas e grupos serão considerados." },
      { q: "O que são 'Gastos do negócio'?", a: "Despesas gerais como aluguel, contabilidade, internet, telefone, software, seguros e marketing." },
      { q: "O que são 'Despesas com pessoal'?", a: "Pró-labore, salários, ajudantes, encargos e benefícios." },
      { q: "O que são 'Despesas operacionais'?", a: "Energia, água, gás, limpeza, manutenção, controle de pragas e despesas semelhantes." },
      { q: "O que entra em 'Embalagem e outros'?", a: "Embalagens gerais, descartáveis, etiquetas, lacres, sacolas e materiais de apoio que você deseja distribuir pelo negócio." },
      { q: "Preciso cadastrar todas as despesas do meu negócio?", a: "Não. Cadastre apenas o que for útil para representar sua realidade de produção." },
      { q: "Posso cadastrar apenas algumas despesas?", a: "Sim. Você pode começar com as principais e ampliar depois." },
      { q: "O que significa deixar uma despesa ativa ou inativa?", a: "Ativa significa disponível para entrar no Custo do Negócio. Inativa permanece cadastrada, mas não é considerada." },
      { q: "Uma despesa inativa é apagada?", a: "Não. Ela continua cadastrada e pode ser reativada quando necessário." },
      { q: "Posso alterar o valor de uma despesa depois?", a: "Sim. Atualize o valor quando sua realidade mudar." },
      { q: "Os valores das despesas devem ser mensais?", a: "Sim. O modelo do Laboratório foi estruturado a partir de valores mensais." },
      { q: "Como cadastrar uma despesa que varia todos os meses?", a: "Você pode usar um valor médio representativo ou atualizar o cadastro periodicamente." },
      { q: "O que faço com energia, água e gás quando os valores mudam?", a: "Atualize quando considerar necessário ou trabalhe com uma média que represente sua operação." },
      { q: "Onde cadastro pró-labore?", a: "Em 'Despesas com pessoal'." },
      { q: "Onde cadastro salário de ajudantes?", a: "Em 'Despesas com pessoal'." },
      { q: "Onde cadastro aluguel?", a: "Em 'Gastos do negócio'." },
      { q: "Onde cadastro embalagens gerais?", a: "Em 'Embalagem e outros'." },
      { q: "Onde cadastro software, telefone ou internet?", a: "Em 'Gastos do negócio'." },
      { q: "O que é o Custo do Negócio?", a: "É uma forma de distribuir as despesas gerais da atividade entre as receitas produzidas." },
      { q: "Por que distribuir minhas despesas entre as receitas?", a: "Porque ingredientes e embalagens específicas não representam todo o custo de manter o negócio funcionando." },
      { q: "O que significa 'Aplicar nos cálculos'?", a: "Determina se o Custo do Negócio será acrescentado aos novos cálculos de receita." },
      { q: "Posso manter as despesas cadastradas sem aplicá-las?", a: "Sim. Basta deixar 'Aplicar nos cálculos' desligado." },
      { q: "Qual é a diferença entre base Dia e base Mês?", a: "Dia utiliza dias de produção e produção média diária. Mês utiliza diretamente a produção média mensal." },
      { q: "Como funciona a distribuição por Dia?", a: "Despesas mensais consideradas ÷ dias de produção no mês ÷ produção média diária = Custo do Negócio por receita." },
      { q: "O que significa 'Dias de produção por mês'?", a: "Quantos dias, em média, você efetivamente produz durante um mês." },
      { q: "O que significa 'Produção média por dia'?", a: "Quantos rendimentos completos de receitas você produz, em média, em cada dia de produção." },
      { q: "Como funciona a distribuição por Mês?", a: "Despesas mensais consideradas ÷ quantidade média de receitas produzidas no mês = Custo do Negócio por receita." },
      { q: "O que significa 'Produção média por mês'?", a: "Quantidade de rendimentos completos de receitas produzidos, em média, durante o mês." },
      { q: "O que devo considerar como uma receita produzida?", a: "Um rendimento completo da receita cadastrada no Laboratório de Cozinha." },
      { q: "Se eu produzir 20 bolos, isso conta como 20 receitas?", a: "Se cada bolo corresponder a um rendimento completo da receita, sim." },
      { q: "Preciso informar horas trabalhadas?", a: "Não. O modelo atual distribui despesas pela produção, e não pelo tempo gasto em cada receita." },
      { q: "Por que o sistema não utiliza custo/hora?", a: "Porque o modelo escolhido representa melhor operações em que a quantidade produzida é a referência principal e o tempo diário pode variar sem mudar o número de produtos entregues." },
      { q: "Como escolher quais grupos de despesas entram no Custo do Negócio?", a: "Marque os grupos que deseja considerar na configuração do Custo do Negócio." },
      { q: "Posso incluir despesas com pessoal?", a: "Sim. Despesas com pessoal podem fazer parte do Custo do Negócio." },
      { q: "Posso excluir embalagens gerais do Custo do Negócio?", a: "Sim. Deixe o grupo desmarcado ou a despesa específica inativa quando não quiser distribuí-la." },
      { q: "Posso alterar os grupos considerados depois?", a: "Sim. A nova configuração será utilizada nos próximos cálculos." },
      { q: "O valor aplicado às fichas antigas será alterado se eu mudar as despesas?", a: "Não. Fichas já salvas preservam o Custo do Negócio utilizado na data do cálculo." },
      { q: "O que é 'Custo médio de comercialização'?", a: "É um percentual global opcional para representar custos variáveis relacionados à comercialização e apoiar a formação avançada do preço." },
      { q: "O percentual de comercialização é obrigatório?", a: "Não. Você pode deixá-lo desligado." },
      { q: "O valor sugerido de 20% é uma regra?", a: "Não. É apenas um valor inicial de referência e deve ser ajustado à realidade do seu negócio." },
      { q: "Posso alterar esse percentual?", a: "Sim. Informe o percentual que melhor represente seus custos médios de comercialização." },
      { q: "Devo cadastrar impostos individualmente?", a: "Não é necessário no modelo simplificado atual. O Laboratório não pretende substituir cálculo fiscal ou contábil." },
      { q: "Preciso informar taxas de cartão separadamente?", a: "Não no fluxo simplificado atual. Custos comerciais podem ser trabalhados de forma agregada pelo percentual médio de comercialização." },
      { q: "Onde esse percentual é utilizado?", a: "Na Formação avançada do preço, quando estiver ativado." },
      { q: "O percentual de comercialização altera o custo técnico da receita?", a: "Não. Ele participa da formação do preço, não do custo técnico importado da receita." }
    ]
  },

  "Custos — Configurações": {
    context: "Configurações guarda os padrões que servem como ponto de partida para novos cálculos. Hoje o principal parâmetro é a margem inicial sugerida. Ela não determina o preço que você deve cobrar e não altera fichas antigas: apenas facilita o começo de cada novo cálculo.",
    faqs: [
      { q: "Para que serve a tela Configurações?", a: "Para definir parâmetros gerais utilizados como ponto de partida nos novos cálculos do Laboratório de Custos." },
      { q: "O que significa 'Margem inicial sugerida'?", a: "É a margem que aparece inicialmente quando você começa a formar o preço de uma receita." },
      { q: "Por que o padrão inicial é 20%?", a: "Para oferecer um ponto de partida simples e editável. Esse percentual não é uma regra de precificação." },
      { q: "A margem inicial de 20% é obrigatória?", a: "Não. Você pode alterar o padrão global e também usar uma margem diferente em cada cálculo." },
      { q: "Posso utilizar uma margem diferente para cada receita?", a: "Sim. A margem padrão só inicia o cálculo; qualquer receita pode ter uma margem diferente." },
      { q: "Se eu alterar a margem padrão, minhas fichas antigas serão alteradas?", a: "Não. Fichas salvas preservam os valores usados na data do cálculo." },
      { q: "A margem padrão muda os cálculos já salvos?", a: "Não. Ela afeta somente novos cálculos que ainda não tiveram o preço comandado por outro campo." },
      { q: "Qual é a diferença entre margem padrão e margem utilizada em uma receita?", a: "A margem padrão é apenas o ponto de partida. A margem efetivamente utilizada em uma receita é aquela definida no próprio cálculo." },
      { q: "O que acontece quando eu altero a margem durante um cálculo?", a: "O preço de venda e o markup são recalculados automaticamente." },
      { q: "Por que o markup não é configurado como padrão?", a: "Porque o fluxo atual inicia pela margem, que costuma ser mais intuitiva para avaliar quanto do preço permanece depois do custo. O markup correspondente é calculado automaticamente." },
      { q: "Qual é a relação entre margem e markup?", a: "Ambos relacionam custo e preço, mas usam bases diferentes: margem é percentual sobre o preço; markup é multiplicador sobre o custo." },
      { q: "Onde configuro o Custo do Negócio?", a: "Em 'Minhas Despesas'." },
      { q: "Por que as despesas não são cadastradas nesta tela?", a: "Para separar parâmetros gerais da gestão das despesas mensais propriamente dita." },
      { q: "Onde configuro o percentual médio de comercialização?", a: "Em 'Minhas Despesas'." },
      { q: "Preciso revisar as Configurações antes de cada cálculo?", a: "Não. Atualize apenas quando sua estratégia ou realidade do negócio mudar." },
      { q: "Quando devo atualizar minhas configurações?", a: "Quando quiser mudar o ponto de partida usado nos novos cálculos, como a margem inicial sugerida." },
      { q: "As configurações valem para todas as receitas?", a: "Elas funcionam como padrões gerais para novos cálculos, mas podem ser substituídas dentro de cada cálculo." },
      { q: "Posso alterar uma configuração somente para um cálculo?", a: "Parâmetros como preço, margem e markup podem ser alterados diretamente no cálculo sem mudar o padrão global." }
    ]
  },

  "Custos — Planos": {
    context: "A tela Planos mostra a oferta preparada para o Laboratório de Custos dentro do mesmo ambiente do Laboratório de Cozinha. Nesta fase ela serve para homologação: os valores e o fluxo do trial estão cadastrados, mas contratação, checkout e Mercado Pago continuam desligados até a publicação comercial.",
    faqs: [
      { q: "Quais planos do Laboratório de Custos estão cadastrados?", a: "7 dias grátis, 30 dias por R$ 8,90 e plano anual por R$ 87,00." },
      { q: "Os planos já estão disponíveis para compra?", a: "Não. Nesta fase a tela está em homologação e os botões de contratação permanecem desativados." },
      { q: "O teste grátis já está liberado para usuários?", a: "Não. O trial de 7 dias está tecnicamente preparado, mas a chave trial_habilitado permanece desligada até a liberação comercial." },
      { q: "O trial pode ser usado mais de uma vez?", a: "Não. A regra preparada permite uma única utilização do trial por usuário." },
      { q: "Preciso ter o Laboratório de Cozinha para usar o Laboratório de Custos?", a: "Sim. O Laboratório de Custos é um complemento e depende de um acesso ativo ao Laboratório de Cozinha." },
      { q: "O que acontece com minhas fichas se o acesso ao Custos expirar?", a: "As fichas e o histórico permanecem preservados. Uma futura reativação restaura o acesso aos registros existentes." },
      { q: "O plano de 30 dias renova automaticamente?", a: "Não no modelo atualmente definido. Ele representa 30 dias de acesso, sem renovação automática." },
      { q: "O plano anual renova automaticamente?", a: "Não no modelo atualmente definido. Ele representa 365 dias de acesso, sem renovação automática." },
      { q: "O Mercado Pago já está integrado a estes planos?", a: "Não. A integração de pagamento continua desligada e será realizada somente após homologação da arquitetura comercial definitiva." },
      { q: "Por que vejo os planos se eles ainda não estão publicados?", a: "Contas administrativas podem visualizar a experiência de homologação para conferir preços, textos, fluxo do trial e estados comerciais antes da publicação." }
    ]
  }
};
