import { createClientFromRequest } from 'npm:@base44/sdk@0.8.43';
import { construirIndiceNomes, construirIndiceSinonimos, construirIndiceAliasesSeguros, classificarDivergenciaIngrediente, normIngrediente } from '../../shared/divergenciaIngrediente.ts';

const txt = (v:any) => v == null ? '' : String(v).trim();
async function all(entity:any, sort='created_date') { const out:any[]=[]; let skip=0; while(true){ const p=await entity.list(sort,500,skip); if(!p?.length) break; out.push(...p); if(p.length<500) break; skip+=p.length; } return out; }
function fonte(item:any,map:Map<string,any>){ let a=item; const seen=new Set<string>(); for(let d=0;d<12&&a?.subreceita_parent_id;d++){ const id=txt(a.subreceita_origem_item_id); if(!id||seen.has(id)) return null; seen.add(id); a=map.get(id); if(!a) return null; } return a?.tipo==='ingrediente'?a:null; }
function pri(n:number){ return n>=20?'alta':n>=5?'media':'baixa'; }
Deno.serve(async(req)=>{ try {
  const b=createClientFromRequest(req); const sr=b.asServiceRole.entities;
  const u=new URL(req.url); const mode=u.searchParams.get('mode')||'dry_run'; if(!['dry_run','apply'].includes(mode)) return Response.json({error:'mode inválido'},{status:400});
  const [receitas,ingredientes,itens,sinonimos,estados]=await Promise.all([all(sr.Receita),all(sr.Ingrediente,'nome'),all(sr.IngredienteReceita),all(sr.SinonimosIngredientes,'sinonimo'),all(sr.CuradoriaDivergenciaIngrediente,'-updated_date')]);
  const rm=new Map(receitas.map((r:any)=>[r.id,r])); const im=new Map(ingredientes.map((i:any)=>[i.id,i])); const itemMap=new Map(itens.map((i:any)=>[i.id,i]));
  const ni=construirIndiceNomes(ingredientes), si=construirIndiceSinonimos(sinonimos), ai=construirIndiceAliasesSeguros(ni); const grupos=new Map<string,any>();
  for(const item of itens){ if(!item||item.tipo!=='ingrediente') continue; const m=im.get(txt(item.ingrediente_id)); if(!m||!txt(item.ingrediente_nome)||normIngrediente(item.ingrediente_nome)===normIngrediente(m.nome)) continue; const f=fonte(item,itemMap); if(!f) continue; const mf=im.get(txt(f.ingrediente_id)); if(!mf) continue; const c=classificarDivergenciaIngrediente({item:f,ingredienteAtual:mf,ingredienteMap:im,nomeIndex:ni,sinonimoIndex:si,aliasSeguroIndex:ai}); if(!c.divergente||c.acao!=='manual') continue;
    const key=`idnome|${normIngrediente(f.ingrediente_nome)||'SEM_NOME'}|${txt(f.ingrediente_id)||'SEM_ID'}|${c.motivo}`; if(!grupos.has(key)) grupos.set(key,{grupo_chave:key,nome_cache:f.ingrediente_nome||item.ingrediente_nome||mf.nome,ingrediente_origem_id:f.ingrediente_id,ingrediente_origem_nome:mf.nome,tipo_conflito:c.motivo,ocorrencias:0,receitas:new Set<string>(),source_item_ids:new Set<string>(),exemplos:[]}); const g=grupos.get(key); g.ocorrencias++; if(item.receita_id) g.receitas.add(item.receita_id); if(f.id) g.source_item_ids.add(f.id); const rn=rm.get(item.receita_id)?.nome; if(rn&&g.exemplos.length<6&&!g.exemplos.includes(rn)) g.exemplos.push(rn);
  }
  const live=[...grupos.values()].map((g:any)=>({...g,receitas_n:g.receitas.size,source_item_ids:[...g.source_item_ids],prioridade:pri(g.receitas.size)})).sort((a:any,b:any)=>b.ocorrencias-a.ocorrencias); const total=live.reduce((s:number,g:any)=>s+g.ocorrencias,0);
  if(mode==='dry_run') return Response.json({mode,total_ocorrencias:total,total_grupos:live.length,queue_records:live.map((g:any)=>({grupo_chave:g.grupo_chave,nome_cache:g.nome_cache,ingrediente_origem_id:g.ingrediente_origem_id,ingrediente_origem_nome:g.ingrediente_origem_nome,tipo_conflito:g.tipo_conflito,workflow_status:'nao_analisado',prioridade:g.prioridade,ocorrencias:g.ocorrencias,receitas:g.receitas_n,detalhes:JSON.stringify({exemplos:g.exemplos,source_item_ids:g.source_item_ids})})),top:live.slice(0,30).map((g:any)=>({nome:g.nome_cache,motivo:g.tipo_conflito,ocorrencias:g.ocorrencias,receitas:g.receitas_n,fontes:g.source_item_ids.length,prioridade:g.prioridade}))});
  const em=new Map<string,any>(); for(const e of estados) if(txt(e.grupo_chave)&&!em.has(e.grupo_chave)) em.set(e.grupo_chave,e); const keys=new Set(live.map((g:any)=>g.grupo_chave)); let criados=0,atualizados=0,resolvidos=0;
  for(const g of live){ const e=em.get(g.grupo_chave); const detalhes=JSON.stringify({exemplos:g.exemplos,source_item_ids:g.source_item_ids}); if(e){ await sr.CuradoriaDivergenciaIngrediente.update(e.id,{nome_cache:g.nome_cache,ingrediente_origem_id:g.ingrediente_origem_id,ingrediente_origem_nome:g.ingrediente_origem_nome,tipo_conflito:g.tipo_conflito,workflow_status:e.workflow_status==='resolvido'?'nao_analisado':(e.workflow_status||'nao_analisado'),prioridade:e.prioridade||g.prioridade,ocorrencias:g.ocorrencias,receitas:g.receitas_n,detalhes}); atualizados++; } else { await sr.CuradoriaDivergenciaIngrediente.create({grupo_chave:g.grupo_chave,nome_cache:g.nome_cache,ingrediente_origem_id:g.ingrediente_origem_id,ingrediente_origem_nome:g.ingrediente_origem_nome,tipo_conflito:g.tipo_conflito,workflow_status:'nao_analisado',prioridade:g.prioridade,ocorrencias:g.ocorrencias,receitas:g.receitas_n,detalhes}); criados++; } }
  for(const e of estados){ if(!txt(e.grupo_chave)||keys.has(e.grupo_chave)||e.workflow_status==='resolvido') continue; await sr.CuradoriaDivergenciaIngrediente.update(e.id,{workflow_status:'resolvido',decisao:e.decisao||'resolvido_fora_da_curadoria'}); resolvidos++; }
  return Response.json({mode,total_ocorrencias:total,total_grupos:live.length,criados,atualizados,resolvidos,top:live.slice(0,30).map((g:any)=>({nome:g.nome_cache,motivo:g.tipo_conflito,ocorrencias:g.ocorrencias,receitas:g.receitas_n,fontes:g.source_item_ids.length,prioridade:g.prioridade}))});
}catch(e:any){console.error(e);return Response.json({error:e?.message||String(e)},{status:500});}});
