-- Baseline generated by Supabase Branching from project aibqicflleqxkotoyvtx.
-- Version 20260904194502 is already recorded in the remote migration ledger.
-- This file contains schema only; no production rows or secrets are included.

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "labcozinha";

ALTER SCHEMA "labcozinha" OWNER TO "postgres";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;

ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "labcozinha"."id_map" (
    "entity_name" "text" NOT NULL,
    "source_id" "text" NOT NULL,
    "target_id" "text" NOT NULL,
    "migrated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "labcozinha"."id_map" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "labcozinha"."migration_batch" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "entity_name" "text" NOT NULL,
    "started_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "finished_at" timestamp with time zone,
    "source_count" bigint,
    "target_count" bigint,
    "source_checksum" "text",
    "target_checksum" "text",
    "status" "text" NOT NULL,
    "notes" "text",
    CONSTRAINT "migration_batch_status_check" CHECK (("status" = ANY (ARRAY['started'::"text", 'validated'::"text", 'failed'::"text", 'rolled_back'::"text"])))
);

ALTER TABLE "labcozinha"."migration_batch" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "labcozinha"."reconciliation_report" (
    "id" bigint NOT NULL,
    "checked_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "metric" "text" NOT NULL,
    "value" bigint NOT NULL,
    "status" "text" NOT NULL,
    "details" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL
);

ALTER TABLE "labcozinha"."reconciliation_report" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "labcozinha"."reconciliation_report_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE "labcozinha"."reconciliation_report_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "labcozinha"."reconciliation_report_id_seq" OWNED BY "labcozinha"."reconciliation_report"."id";

CREATE TABLE IF NOT EXISTS "labcozinha"."records" (
    "entity_name" "text" NOT NULL,
    "id" "text" NOT NULL,
    "created_date" timestamp with time zone,
    "updated_date" timestamp with time zone,
    "created_by_id" "text",
    "payload" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "source_checksum" "text"
);

ALTER TABLE "labcozinha"."records" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "labcozinha"."storage_manifest" (
    "source_entity" "text" NOT NULL,
    "source_record_id" "text" NOT NULL,
    "source_field" "text" NOT NULL,
    "source_uri" "text" NOT NULL,
    "source_visibility" "text" NOT NULL,
    "owner_user_id" "text",
    "business_class" "text" NOT NULL,
    "destination_bucket" "text" NOT NULL,
    "destination_path" "text",
    "destination_uri" "text",
    "http_status" integer,
    "mime_detected" "text",
    "size_bytes" bigint,
    "sha256" "text",
    "migration_status" "text" NOT NULL,
    "attempt_count" integer DEFAULT 0 NOT NULL,
    "last_error" "text",
    "migrated_at" timestamp with time zone,
    "verified_at" timestamp with time zone
);

ALTER TABLE "labcozinha"."storage_manifest" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "labcozinha"."user_profiles_shadow" (
    "source_user_id" "text" NOT NULL,
    "email" "text" NOT NULL,
    "full_name" "text",
    "role" "text" NOT NULL,
    "payload" "jsonb" NOT NULL,
    "source_created_at" timestamp with time zone,
    "source_updated_at" timestamp with time zone,
    "auth_migration_status" "text" DEFAULT 'staged'::"text" NOT NULL,
    "target_auth_user_id" "uuid",
    "migrated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "user_profiles_shadow_auth_migration_status_check" CHECK (("auth_migration_status" = ANY (ARRAY['staged'::"text", 'auth_created'::"text", 'reset_sent'::"text", 'verified'::"text", 'failed'::"text"])))
);

ALTER TABLE "labcozinha"."user_profiles_shadow" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "source_user_id" "text" NOT NULL,
    "full_name" "text",
    "email" "text" NOT NULL,
    "role" "text" NOT NULL,
    "telefone_whatsapp" "text",
    "empresa" "text",
    "plano_atual" "text",
    "status_assinatura" "text",
    "data_inicio" "date",
    "data_expiracao" "date",
    "trial_modelo" "text",
    "trial_dias_uso" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "data_proxima_cobranca" "date",
    "ciclo_renovacao" integer DEFAULT 0 NOT NULL,
    "pagamento_ativo_id" "text",
    "cpf_cnpj" "text",
    "razao_social" "text",
    "cep" "text",
    "cidade_uf" "text",
    "endereco" "text",
    "segmento" "text",
    "origem" "text",
    "termos_aceitos_em" timestamp with time zone,
    "termos_versao_aceita" "text",
    "privacidade_versao_aceita" "text",
    "force_password_reset" boolean DEFAULT true NOT NULL,
    "source_created_at" timestamp with time zone,
    "source_updated_at" timestamp with time zone,
    "migrated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['admin'::"text", 'user'::"text"])))
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

ALTER TABLE ONLY "labcozinha"."reconciliation_report" ALTER COLUMN "id" SET DEFAULT "nextval"('"labcozinha"."reconciliation_report_id_seq"'::"regclass");

ALTER TABLE ONLY "labcozinha"."id_map"
    ADD CONSTRAINT "id_map_entity_name_target_id_key" UNIQUE ("entity_name", "target_id");

ALTER TABLE ONLY "labcozinha"."id_map"
    ADD CONSTRAINT "id_map_pkey" PRIMARY KEY ("entity_name", "source_id");

ALTER TABLE ONLY "labcozinha"."migration_batch"
    ADD CONSTRAINT "migration_batch_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "labcozinha"."reconciliation_report"
    ADD CONSTRAINT "reconciliation_report_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "labcozinha"."records"
    ADD CONSTRAINT "records_pkey" PRIMARY KEY ("entity_name", "id");

ALTER TABLE ONLY "labcozinha"."storage_manifest"
    ADD CONSTRAINT "storage_manifest_pkey" PRIMARY KEY ("source_entity", "source_record_id", "source_field");

ALTER TABLE ONLY "labcozinha"."user_profiles_shadow"
    ADD CONSTRAINT "user_profiles_shadow_pkey" PRIMARY KEY ("source_user_id");

ALTER TABLE ONLY "labcozinha"."user_profiles_shadow"
    ADD CONSTRAINT "user_profiles_shadow_target_auth_user_id_key" UNIQUE ("target_auth_user_id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_source_user_id_key" UNIQUE ("source_user_id");

CREATE INDEX "records_creator_idx" ON "labcozinha"."records" USING "btree" ("entity_name", "created_by_id");

CREATE INDEX "records_payload_gin" ON "labcozinha"."records" USING "gin" ("payload");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Auth is intentionally disabled in the local database-only stack. On hosted
-- projects auth.jwt() exists, so the pulled legacy policy is recreated exactly.
DO $remote_schema$
BEGIN
  IF to_regprocedure('auth.jwt()') IS NOT NULL THEN
    EXECUTE $policy$
      CREATE POLICY "profile owner or admin read"
      ON "public"."profiles"
      FOR SELECT
      TO "authenticated"
      USING (
        ("id" = "auth"."uid"())
        OR (
          (("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text")
          = 'admin'::"text"
        )
      )
    $policy$;
  END IF;
END
$remote_schema$;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "anon";

GRANT USAGE ON SCHEMA "public" TO "authenticated";

GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";

GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";

GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";

-- The hosted baseline above is already represented by the remote ledger. A
-- fresh/local replay must not expose the SECURITY DEFINER routine, even for the
-- short interval between this baseline and the reconciliation migration.
REVOKE EXECUTE ON FUNCTION "public"."rls_auto_enable"()
  FROM PUBLIC, "anon", "authenticated";

GRANT ALL ON TABLE "public"."profiles" TO "anon";

GRANT ALL ON TABLE "public"."profiles" TO "authenticated";

GRANT ALL ON TABLE "public"."profiles" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
